<?php
/**
 * Title: Caards Editorial Homepage
 * Slug: digipublish/caards-home
 * Categories: digipublish
 * Inserter: true
 */
?>
<!-- wp:group {"align":"full","className":"dp-caards-home-hero","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull dp-caards-home-hero"><!-- wp:group {"align":"wide","className":"dp-caards-home-hero__inner","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide dp-caards-home-hero__inner"><!-- wp:paragraph {"align":"center","className":"dp-caards-eyebrow","fontSize":"xs"} --><p class="has-text-align-center dp-caards-eyebrow has-xs-font-size">Revolutionizing Technological Frontiers</p><!-- /wp:paragraph --><!-- wp:heading {"textAlign":"center","level":1,"fontSize":"4xl"} --><h1 class="wp-block-heading has-text-align-center has-4-xl-font-size">Tech it to the Limit<br>Join the Tech Revolution Today</h1><!-- /wp:heading --><!-- wp:paragraph {"align":"center","className":"dp-caards-home-hero__lead","fontSize":"md"} --><p class="has-text-align-center dp-caards-home-hero__lead has-md-font-size">Join the community of curious readers and explore the stories shaping technology, business, culture and tomorrow.</p><!-- /wp:paragraph --><!-- wp:digipublish/category-nav {"limit":8,"showDictionary":false,"showSearch":false} /--></div><!-- /wp:group --></div><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"dp-caards-home-grid","layout":{"type":"default"}} --><div class="wp-block-group alignwide dp-caards-home-grid"><!-- wp:digipublish/post-feed {"heading":"","postsToShow":5,"layout":"tile-3","columnsDesktop":4,"showExcerpt":false,"showAuthor":false,"showDate":true,"showReadTime":true,"showCategory":true} /--></div><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"dp-caards-home-section","layout":{"type":"default"}} --><div class="wp-block-group alignwide dp-caards-home-section"><!-- wp:digipublish/post-feed {"heading":"Latest Stories","postsToShow":8,"layout":"standard-1","columnsDesktop":4,"columnsTablet":2,"columnsMobile":1,"showExcerpt":true,"showAuthor":false,"showDate":true,"showReadTime":true,"showCategory":true} /--></div><!-- /wp:group -->
<!-- wp:group {"align":"wide","className":"dp-caards-home-section","layout":{"type":"default"}} --><div class="wp-block-group alignwide dp-caards-home-section"><!-- wp:digipublish/post-feed {"heading":"Trending Now","postsToShow":6,"layout":"carousel-1","columnsDesktop":3,"columnsTablet":2,"columnsMobile":1,"orderBy":"comment_count","showExcerpt":false,"showAuthor":false,"showDate":true,"showCategory":true} /--></div><!-- /wp:group -->
<!-- wp:group {"anchor":"newsletter","align":"wide","className":"dp-caards-newsletter","layout":{"type":"constrained"}} --><div id="newsletter" class="wp-block-group alignwide dp-caards-newsletter"><!-- wp:pattern {"slug":"digipublish/newsletter"} /--></div><!-- /wp:group -->